export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SEARCH_CAR_BRANDS = "SEARCH_CAR_BRANDS";
export const GET_PAGING_CAR_BRANDS = "GET_PAGING_CAR_BRANDS";
export const SHOW_MODAL_CAR_BRANDS = "SHOW_MODAL_CAR_BRANDS";
export const ADD_CAR_BRANDS = "ADD_CAR_BRANDS";
export const UPDATE_CAR_BRANDS = "UPDATE_CAR_BRANDS";
export const DELETE_CAR_BRANDS = "DELETE_CAR_BRANDS";
export const PAGE_CHANGE_CAR_BRANDS = "PAGE_CHANGE_CAR_BRANDS";

export const SEARCH_SUPPLIERS = "SEARCH_SUPPLIERS";
export const GET_PAGING_SUPPLIERS = "GET_PAGING_SUPPLIERS";
export const SHOW_MODAL_SUPPLIERS = "SHOW_MODAL_SUPPLIERS";
export const ADD_SUPPLIERS = "ADD_SUPPLIERS";
export const UPDATE_SUPPLIERS = "UPDATE_SUPPLIERS";
export const DELETE_SUPPLIERS = "DELETE_SUPPLIERS";
export const PAGE_CHANGE_SUPPLIERS = "PAGE_CHANGE_SUPPLIERS";
export const RESET_SUPPLIERS = "RESET_SUPPLIERS";

export const SEARCH_CUSTOMER_TYPES = "SEARCH_CUSTOMER_TYPES";
export const GET_PAGING_CUSTOMER_TYPES = "GET_PAGING_CUSTOMER_TYPES";
export const SHOW_MODAL_CUSTOMER_TYPES = "SHOW_MODAL_CUSTOMER_TYPES";
export const ADD_CUSTOMER_TYPES = "ADD_CUSTOMER_TYPES";
export const UPDATE_CUSTOMER_TYPES = "UPDATE_CUSTOMER_TYPES";
export const DELETE_CUSTOMER_TYPES = "DELETE_CUSTOMER_TYPES";
export const PAGE_CHANGE_CUSTOMER_TYPES = "PAGE_CHANGE_CUSTOMER_TYPES";

export const SEARCH_CATEGORIES = "SEARCH_CATEGORIES";
export const GET_PAGING_CATEGORIES = "GET_PAGING_CATEGORIES";
export const SHOW_MODAL_CATEGORIES = "SHOW_MODAL_CATEGORIES";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const PAGE_CHANGE_CATEGORIES = "PAGE_CHANGE_CATEGORIES";

export const SEARCH_CUSTOMERS = "SEARCH_CUSTOMERS";
export const GET_PAGING_CUSTOMERS = "GET_PAGING_CUSTOMERS";
export const SHOW_MODAL_CUSTOMERS = "SHOW_MODAL_CUSTOMERS";
export const ADD_CUSTOMERS = "ADD_CUSTOMERS";
export const UPDATE_CUSTOMERS = "UPDATE_CUSTOMERS";
export const DELETE_CUSTOMERS = "DELETE_CUSTOMERS";
export const PAGE_CHANGE_CUSTOMERS = "PAGE_CHANGE_CUSTOMERS";
export const RESET_CUSTOMERS = "RESET_CUSTOMERS";

export const SEARCH_CARS = "SEARCH_CARS";
export const GET_PAGING_CARS = "GET_PAGING_CARS";
export const SHOW_MODAL_CARS = "SHOW_MODAL_CARS";
export const ADD_CARS = "ADD_CARS";
export const UPDATE_CARS = "UPDATE_CARS";
export const DELETE_CARS = "DELETE_CARS";
export const PAGE_CHANGE_CARS = "PAGE_CHANGE_CARS";

export const SEARCH_RECEIVE_VOTES = "SEARCH_RECEIVE_VOTES";
export const GET_PAGING_RECEIVE_VOTES = "GET_PAGING_RECEIVE_VOTES";
export const SHOW_MODAL_RECEIVE_VOTES = "SHOW_MODAL_RECEIVE_VOTES";
export const ADD_RECEIVE_VOTES = "ADD_RECEIVE_VOTES";
export const UPDATE_RECEIVE_VOTES = "UPDATE_RECEIVE_VOTES";
export const DELETE_RECEIVE_VOTES = "DELETE_RECEIVE_VOTES";
export const PAGE_CHANGE_RECEIVE_VOTES = "PAGE_CHANGE_RECEIVE_VOTES";
export const BIDDING_RECEIVE_VOTES = "BIDDING_RECEIVE_VOTES";
export const INPUT_CHANGE_RECEIVE_VOTES = "INPUT_CHANGE_RECEIVE_VOTES";
export const RESET_FORM_RECEIVE_VOTES = "RESET_FORM_RECEIVE_VOTES";
export const RELOAD_RECEIVE_VOTES = "RELOAD_RECEIVE_VOTES";
export const FILLTER_DATE_RECEIVE_VOTES = "FILLTER_DATE_RECEIVE_VOTES";
export const CHANGE_ROW_RECEIVE_VOTES = "CHANGE_ROW_RECEIVE_VOTES";
export const CANCEL_RECEIVE_VOTES = "CANCEL_RECEIVE_VOTES";
export const CHANGE_STATUS_RECEIVE_VOTES = "CHANGE_STATUS_RECEIVE_VOTES";
export const CLEAR_DATE_RECEIVE_VOTES = "CLEAR_DATE_RECEIVE_VOTES";

export const SEARCH_PRODUCT_TYPES = "SEARCH_PRODUCT_TYPES";
export const GET_PAGING_PRODUCT_TYPES = "GET_PAGING_PRODUCT_TYPES";
export const SHOW_MODAL_PRODUCT_TYPES = "SHOW_MODAL_PRODUCT_TYPES";
export const ADD_PRODUCT_TYPES = "ADD_PRODUCT_TYPES";
export const UPDATE_PRODUCT_TYPES = "UPDATE_PRODUCT_TYPES";
export const DELETE_PRODUCT_TYPES = "DELETE_PRODUCT_TYPES";
export const PAGE_CHANGE_PRODUCT_TYPES = "PAGE_CHANGE_PRODUCT_TYPES";

export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const GET_PAGING_PRODUCTS = "GET_PAGING_PRODUCTS";
export const SHOW_MODAL_PRODUCTS = "SHOW_MODAL_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const PAGE_CHANGE_PRODUCTS = "PAGE_CHANGE_PRODUCTS";
export const IMAGE_CHANGE_PRODUCTS = "IMAGE_CHANGE_PRODUCTS";
export const BIDDING_PRODUCTS = "BIDDING_PRODUCTS";

export const SEARCH_REPAIR_VOTES = "SEARCH_REPAIR_VOTES";
export const GET_PAGING_REPAIR_VOTES = "GET_PAGING_REPAIR_VOTES";
export const SHOW_MODAL_REPAIR_VOTES = "SHOW_MODAL_REPAIR_VOTES";
export const ADD_REPAIR_VOTES = "ADD_REPAIR_VOTES";
export const UPDATE_REPAIR_VOTES = "UPDATE_REPAIR_VOTES";
export const DELETE_REPAIR_VOTES = "DELETE_REPAIR_VOTES";
export const PAGE_CHANGE_REPAIR_VOTES = "PAGE_CHANGE_REPAIR_VOTES";
export const IMAGE_CHANGE_REPAIR_VOTES = "IMAGE_CHANGE_REPAIR_VOTES";
export const RELOAD_REPAIR_VOTES = "RELOAD_REPAIR_VOTES";
export const FILLTER_DATE_REPAIR_VOTES = "FILLTER_DATE_REPAIR_VOTES";
export const CHANGE_ROW_REPAIR_VOTES = "CHANGE_ROW_REPAIR_VOTES";
export const CHANGE_STATUS_REPAIR_VOTES = "CHANGE_STATUS_REPAIR_VOTES";
export const CLEAR_DATE_REPAIR_VOTES = "CLEAR_DATE_REPAIR_VOTES";

export const SHOW_MODAL_PRICE_QUOTES = "SHOW_MODAL_PRICE_QUOTES";

export const SEARCH_SERVICE_TYPES = "SEARCH_SERVICE_TYPES";
export const GET_PAGING_SERVICE_TYPES = "GET_PAGING_SERVICE_TYPES";
export const SHOW_MODAL_SERVICE_TYPES = "SHOW_MODAL_SERVICE_TYPES";
export const ADD_SERVICE_TYPES = "ADD_SERVICE_TYPES";
export const UPDATE_SERVICE_TYPES = "UPDATE_SERVICE_TYPES";
export const DELETE_SERVICE_TYPES = "DELETE_SERVICE_TYPES";
export const PAGE_CHANGE_SERVICE_TYPES = "PAGE_CHANGE_SERVICE_TYPES";

export const SEARCH_SERVICES = "SEARCH_SERVICES";
export const GET_PAGING_SERVICES = "GET_PAGING_SERVICES";
export const SHOW_MODAL_SERVICES = "SHOW_MODAL_SERVICES";
export const ADD_SERVICES = "ADD_SERVICES";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const DELETE_SERVICES = "DELETE_SERVICES";
export const PAGE_CHANGE_SERVICES = "PAGE_CHANGE_SERVICES";
export const BIDDING_SERVICES = "BIDDING_SERVICES";
export const IMAGE_CHANGE_SERVICES = "IMAGE_CHANGE_SERVICES";

export const ADD_REPAIR_SERVICES = "ADD_REPAIR_SERVICES";
export const RESET_REPAIR_SERVICES = "RESET_REPAIR_SERVICES";
export const DELETE_REPAIR_SERVICES = "DELETE_REPAIR_SERVICES";
export const EDIT_REPAIR_SERVICES = "EDIT_REPAIR_SERVICES";

export const ADD_REPAIR_PRODUCTS = "ADD_REPAIR_PRODUCTS";
export const RESET_REPAIR_PRODUCTS = "RESET_REPAIR_PRODUCTS";
export const DELETE_REPAIR_PRODUCTS = "DELETE_REPAIR_PRODUCTS";
export const EDIT_REPAIR_PRODUCTS = "EDIT_REPAIR_PRODUCTS";

export const SEARCH_FEEDBACKS = "SEARCH_FEEDBACKS";
export const GET_PAGING_FEEDBACKS = "GET_PAGING_FEEDBACKS";
export const SHOW_MODAL_FEEDBACKS = "SHOW_MODAL_FEEDBACKS";
export const PAGE_CHANGE_FEEDBACKS = "PAGE_CHANGE_FEEDBACKS";
export const FILLTER_DATE_FEEDBACKS = "FILLTER_DATE_FEEDBACKS";
export const CHANGE_STAR_FEEDBACKS = "CHANGE_STAR_FEEDBACKS";
export const CLEAR_DATE_FEEDBACKS = "CLEAR_DATE_FEEDBACKS";

export const TOTAL_REPAIR_VOTES = "TOTAL_REPAIR_VOTES";
export const DISCOUNT_REPAIR_VOTES = "DISCOUNT_REPAIR_VOTES";

export const SEARCH_EXPORT_VOTES = "SEARCH_EXPORT_VOTES";
export const GET_PAGING_EXPORT_VOTES = "GET_PAGING_EXPORT_VOTES";
export const SHOW_MODAL_EXPORT_VOTES = "SHOW_MODAL_EXPORT_VOTES";
export const ADD_EXPORT_VOTES = "ADD_EXPORT_VOTES";
export const UPDATE_EXPORT_VOTES = "UPDATE_EXPORT_VOTES";
export const DELETE_EXPORT_VOTES = "DELETE_EXPORT_VOTES";
export const PAGE_CHANGE_EXPORT_VOTES = "PAGE_CHANGE_EXPORT_VOTES";
export const EDIT_EXPORT_PRODUCTS = "EDIT_EXPORT_PRODUCTS";
export const DELETE_EXPORT_PRODUCTS = "DELETE_EXPORT_PRODUCTS";
export const CONFIRM_EXPORT = "CONFIRM_EXPORT";
export const FILLTER_DATE_EXPORT_VOTES = "FILLTER_DATE_EXPORT_VOTES";
export const CHANGE_ROW_EXPORT_VOTES = "CHANGE_ROW_EXPORT_VOTES";
export const CHANGE_STATUS_EXPORT_VOTES = "CHANGE_STATUS_EXPORT_VOTES";
export const CLEAR_DATE_EXPORT_VOTES = "CLEAR_DATE_EXPORT_VOTES";

export const SEARCH_IMPORT_VOTES = "SEARCH_IMPORT_VOTES";
export const GET_PAGING_IMPORT_VOTES = "GET_PAGING_IMPORT_VOTES";
export const SHOW_MODAL_IMPORT_VOTES = "SHOW_MODAL_IMPORT_VOTES";
export const ADD_IMPORT_VOTES = "ADD_IMPORT_VOTES";
export const UPDATE_IMPORT_VOTES = "UPDATE_IMPORT_VOTES";
export const DELETE_IMPORT_VOTES = "DELETE_IMPORT_VOTES";
export const PAGE_CHANGE_IMPORT_VOTES = "PAGE_CHANGE_IMPORT_VOTES";
export const FILLTER_DATE_IMPORT_VOTES = "FILLTER_DATE_IMPORT_VOTES";
export const CHANGE_ROW_IMPORT_VOTES = "CHANGE_ROW_IMPORT_VOTES";
export const ADD_PAYMENT_VOTES = "ADD_PAYMENT_VOTES";
export const IMAGE_CHANGE_IMPORTS = "IMAGE_CHANGE_IMPORTS";
export const CLEAR_DATE_IMPORT_VOTES = "CLEAR_DATE_IMPORT_VOTES";

export const SHOW_MODAL_IMPORT_VOTE_DETAILS = "SHOW_MODAL_IMPORT_VOTE_DETAILS";
export const ADD_IMPORT_VOTE_DETAILS = "ADD_IMPORT_VOTE_DETAILS";
export const UPDATE_IMPORT_VOTE_DETAILS = "UPDATE_IMPORT_VOTE_DETAILS";
export const DELETE_IMPORT_VOTE_DETAILS = "DELETE_IMPORT_VOTE_DETAILS";
export const BIDDING_IMPORT_VOTE_DETAILS = "BIDDING_IMPORT_VOTE_DETAILS";

export const ADD_IMPORT_DETAIL_PRODUCTS = "ADD_IMPORT_DETAIL_PRODUCTS";
export const RESET_IMPORT_DETAIL_PRODUCTS = "RESET_IMPORT_DETAIL_PRODUCTS";
export const EDIT_IMPORT_DETAIL_PRODUCTS = "EDIT_IMPORT_DETAIL_PRODUCTS";
export const DELETE_IMPORT_DETAIL_PRODUCTS = "DELETE_IMPORT_DETAIL_PRODUCTS";
export const TOTAL_IMPORT_DETAIL_PRODUCTS = "TOTAL_IMPORT_DETAIL_PRODUCTS";
export const RELOAD_IMPORT_DETAIL_PRODUCTS = "RELOAD_IMPORT_DETAIL_PRODUCTS";
export const CONFIRM_IMPORT = "CONFIRM_IMPORT";

export const SEARCH_ROLES = "SEARCH_ROLES";
export const GET_PAGING_ROLES = "GET_PAGING_ROLES";
export const SHOW_MODAL_ROLES = "SHOW_MODAL_ROLES";
export const ADD_ROLES = "ADD_ROLES";
export const UPDATE_ROLES = "UPDATE_ROLES";
export const DELETE_ROLES = "DELETE_ROLES";
export const PAGE_CHANGE_ROLES = "PAGE_CHANGE_ROLES";
export const RESET_ROLES = "RESET_ROLES";

export const SEARCH_MENUS = "SEARCH_MENUS";
export const GET_PAGING_MENUS = "GET_PAGING_MENUS";
export const SHOW_MODAL_MENUS = "SHOW_MODAL_MENUS";
export const ADD_MENUS = "ADD_MENUS";
export const UPDATE_MENUS = "UPDATE_MENUS";
export const DELETE_MENUS = "DELETE_MENUS";
export const PAGE_CHANGE_MENUS = "PAGE_CHANGE_MENUS";
export const SET_CHECK_MENUS = "SET_CHECK_MENUS";

export const SHOW_MODAL_DEFAULT_ROLES = "SHOW_MODAL_DEFAULT_ROLES";
export const ADD_DEFAULT_ROLES = "ADD_DEFAULT_ROLES";
export const UPDATE_DEFAULT_ROLES = "UPDATE_DEFAULT_ROLES";
export const SET_CHECK_DEFAULT_ROLES = "SET_CHECK_DEFAULT_ROLES";

export const SHOW_MODAL_CUSTOM_ROLES = "SHOW_MODAL_CUSTOM_ROLES";
export const ADD_CUSTOM_ROLES = "ADD_CUSTOM_ROLES";
export const SET_CHECK_CUSTOM_ROLES = "SET_CHECK_CUSTOM_ROLES";

export const SEARCH_USERS = "SEARCH_USERS";
export const GET_PAGING_USERS = "GET_PAGING_USERS";
export const SHOW_MODAL_USERS = "SHOW_MODAL_USERS";
export const ADD_USERS = "ADD_USERS";
export const UPDATE_USERS = "UPDATE_USERS";
export const DELETE_USERS = "DELETE_USERS";
export const PAGE_CHANGE_USERS = "PAGE_CHANGE_USERS";
export const IMAGE_CHANGE_USERS = "IMAGE_CHANGE_USERS";
export const GET_USER_INFO = "GET_USER_INFO";
export const IMAGE_CHANGE_USER_INFO = "IMAGE_CHANGE_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const SHOW_MODAL_CLIENTS = "SHOW_MODAL_CLIENTS";
export const GET_PAGING_CAR_CLIENTS = "GET_PAGING_CAR_CLIENTS";
export const ADD_CAR_CLIENTS = "ADD_CAR_CLIENTS";
export const UPDATE_CAR_CLIENTS = "UPDATE_CAR_CLIENTS";
export const DELETE_CAR_CLIENTS = "DELETE_CAR_CLIENTS";
export const IMAGE_CHANGE_PROFILE_CLIENTS = "IMAGE_CHANGE_PROFILE_CLIENTS";
export const GET_USER_PROFILES = "GET_USER_PROFILES";
export const UPDATE_PROFILE_USERS = "UPDATE_PROFILE_USERS";
export const UPDATE_AVATAR_USERS = "UPDATE_AVATAR_USERS";
export const RESET_DATA_USERS = "RESET_DATA_USERS";
export const GET_SERVICE_DETAILS = "GET_SERVICE_DETAILS";
export const GET_NEW_DETAILS = "GET_NEW_DETAILS";
export const GET_BOOKING_REPAIRS = "GET_BOOKING_REPAIRS";
export const RELOAD_BOOKING_REPAIR_CLIENTS = "RELOAD_BOOKING_REPAIR_CLIENTS";
export const SET_FEEDBACK_CLIENTS = "SET_FEEDBACK_CLIENTS";
export const CHANGE_RATING_CLIENTS = "CHANGE_RATING_CLIENTS";

export const GET_PAGING_BOOKINGS = "GET_PAGING_BOOKINGS";
export const PAGE_CHANGE_BOOKINGS = "PAGE_CHANGE_BOOKINGS";
export const SEARCH_BOOKINGS = "SEARCH_BOOKINGS";
export const SHOW_MODAL_BOOKINGS = "SHOW_MODAL_BOOKINGS";
export const FILLTER_DATE_BOOKING_VOTES = "FILLTER_DATE_BOOKING_VOTES";
export const CHANGE_ROW_BOOKING_VOTES = "CHANGE_ROW_BOOKING_VOTES";

export const ACCEPT_BOOKINGS = "ACCEPT_BOOKINGS";
export const ACCEPT_REPAIR = "ACCEPT_REPAIR";

export const ADD_COLLECT_VOTES = "ADD_COLLECT_VOTES";

export const GET_HISTORY_REPAIR_CLIENTS = "GET_HISTORY_REPAIR_CLIENTS";

export const RESET_FILLTER = "RESET_FILLTER";

export const GET_DASHBROAD = "GET_DASHBROAD";
export const FILLTER_DATE_DASHBROAD = "FILLTER_DATE_DASHBROAD";
export const CHANGE_DATE_DASHBROAD = "CHANGE_DATE_DASHBROAD";
export const SHOW_MODAL_DASHBOARD = "SHOW_MODAL_DASHBOARD";
export const MULTI_CHANGE_DASHBOARD = "MULTI_CHANGE_DASHBOARD";
export const MULTI_FOCUS_DASHBOARD = "MULTI_FOCUS_DASHBOARD";
export const CHANGE_ADDRESS_DASHBOARD = "CHANGE_ADDRESS_DASHBOARD";
export const SET_DATA_VIEWER_DASHBOARD = "SET_DATA_VIEWER_DASHBOARD";
export const CLEAR_DATE_DASHBOARD = "CLEAR_DATE_DASHBOARD";
export const CLEAR_FILLTER_DASHBOARD = "CLEAR_FILLTER_DASHBOARD";

export const SEARCH_NEWS = "SEARCH_NEWS";
export const GET_PAGING_NEWS = "GET_PAGING_NEWS";
export const SHOW_MODAL_NEWS = "SHOW_MODAL_NEWS";
export const ADD_NEWS = "ADD_NEWS";
export const UPDATE_NEWS = "UPDATE_NEWS";
export const DELETE_NEWS = "DELETE_NEWS";
export const PAGE_CHANGE_NEWS = "PAGE_CHANGE_NEWS";
export const IMAGE_CHANGE_NEWS = "IMAGE_CHANGE_NEWS";

export const GET_SETTING_INFO = "GET_SETTING_INFO";
export const UPDATE_BUSINESS_INFO = "UPDATE_BUSINESS_INFO";
export const IMAGE_CHANGE_BUSINESS = "IMAGE_CHANGE_BUSINESS";
